
import { Player } from './types';

export const INITIAL_BUDGET = 5000;
export const MIN_BID_INCREMENT = 25;
export const BASE_PRICE = 50;

export const FRANCHISES: any[] = [
  { id: 'F1', name: 'Mukesh', budget: INITIAL_BUDGET, roster: [], color: '#004BA0' },
  { id: 'F2', name: 'Vishal', budget: INITIAL_BUDGET, roster: [], color: '#FFFF00' },
  { id: 'F3', name: 'Rakesh', budget: INITIAL_BUDGET, roster: [], color: '#EC1C24' },
  { id: 'F4', name: 'Chintu/Bunty', budget: INITIAL_BUDGET, roster: [], color: '#3A225D' },
  { id: 'F5', name: 'Manish', budget: INITIAL_BUDGET, roster: [], color: '#FF822E' },
  { id: 'F6', name: 'Amit/Kunal', budget: INITIAL_BUDGET, roster: [], color: '#00008B' },
  { id: 'F7', name: 'Mithun', budget: INITIAL_BUDGET, roster: [], color: '#EA1A85' },
  { id: 'F8', name: 'Darpan', budget: INITIAL_BUDGET, roster: [], color: '#0057E7' },
];

const generatePlayer = (name: string, skill: string, originalTeam: string, country: string = 'India', rating: number = 85): Player => ({
  id: `p-${name.toLowerCase().replace(/\s+/g, '-')}`,
  name,
  skill,
  originalTeam,
  basePrice: 50,
  country,
  rating,
  isSold: false
});

export const INITIAL_PLAYERS: Player[] = [
  // Sunrisers Hyderabad
  generatePlayer('Ishan Kishan', 'WK-Batter', 'SRH'),
  generatePlayer('Aniket Verma', 'Batter', 'SRH'),
  generatePlayer('Smaran Ravichandran', 'Batter', 'SRH'),
  generatePlayer('Salil Arora', 'WK-Batter', 'SRH'),
  generatePlayer('Heinrich Klaasen', 'WK-Batter', 'SRH', 'South Africa', 94),
  generatePlayer('Travis Head', 'Batter', 'SRH', 'Australia', 93),
  generatePlayer('Harshal Patel', 'All-Rounder', 'SRH'),
  generatePlayer('Kamindu Mendis', 'All-Rounder', 'SRH', 'Sri Lanka'),
  generatePlayer('Harsh Dubey', 'All-Rounder', 'SRH'),
  generatePlayer('Brydon Carse', 'All-Rounder', 'SRH', 'England'),
  generatePlayer('Shivang Kumar', 'All-Rounder', 'SRH'),
  generatePlayer('Krains Fuletra', 'All-Rounder', 'SRH'),
  generatePlayer('Liam Livingstone', 'All-Rounder', 'SRH', 'England', 90),
  generatePlayer('Jack Edwards', 'All-Rounder', 'SRH', 'Australia'),
  generatePlayer('Abhishek Sharma', 'All-Rounder', 'SRH', 'India', 89),
  generatePlayer('Nitish Kumar Reddy', 'All-Rounder', 'SRH'),
  generatePlayer('Pat Cummins', 'Bowler', 'SRH', 'Australia', 96),
  generatePlayer('Zeeshan Ansari', 'Bowler', 'SRH'),
  generatePlayer('Jaydev Unadkat', 'Bowler', 'SRH'),
  generatePlayer('Eshan Malinga', 'Bowler', 'SRH', 'Sri Lanka'),
  generatePlayer('Sakib Hussain', 'Bowler', 'SRH'),
  generatePlayer('Onkar Tarmale', 'Bowler', 'SRH'),
  generatePlayer('Amit Kumar', 'Bowler', 'SRH'),
  generatePlayer('Praful Hinge', 'Bowler', 'SRH'),
  generatePlayer('Shivam Mavi', 'Bowler', 'SRH'),

  // Chennai Super Kings
  generatePlayer('MS Dhoni', 'WK-Batter', 'CSK', 'India', 95),
  generatePlayer('Sanju Samson', 'WK-Batter', 'CSK', 'India', 91),
  generatePlayer('Ruturaj Gaikwad', 'Batter', 'CSK', 'India', 92),
  generatePlayer('Dewald Brevis', 'Batter', 'CSK', 'South Africa'),
  generatePlayer('Ayush Mhatre', 'Batter', 'CSK'),
  generatePlayer('Kartik Sharma', 'WK-Batter', 'CSK'),
  generatePlayer('Sarfaraz Khan', 'Batter', 'CSK'),
  generatePlayer('Urvil Patel', 'WK-Batter', 'CSK'),
  generatePlayer('Anshul Kamboj', 'All-Rounder', 'CSK'),
  generatePlayer('Jamie Overton', 'All-Rounder', 'CSK', 'England'),
  generatePlayer('Ramakrishna Ghosh', 'All-Rounder', 'CSK'),
  generatePlayer('Prashant Veer', 'All-Rounder', 'CSK'),
  generatePlayer('Matthew William Short', 'All-Rounder', 'CSK', 'Australia'),
  generatePlayer('Aman Khan', 'All-Rounder', 'CSK'),
  generatePlayer('Zak Foulkes', 'All-Rounder', 'CSK', 'New Zealand'),
  generatePlayer('Shivam Dube', 'All-Rounder', 'CSK', 'India', 89),
  generatePlayer('Khaleel Ahmed', 'Bowler', 'CSK'),
  generatePlayer('Noor Ahmad', 'Bowler', 'CSK', 'Afghanistan'),
  generatePlayer('Mukesh Choudhary', 'Bowler', 'CSK'),
  generatePlayer('Nathan Ellis', 'Bowler', 'CSK', 'Australia'),
  generatePlayer('Shreyas Gopal', 'Bowler', 'CSK'),
  generatePlayer('Gurjapneet Singh', 'Bowler', 'CSK'),
  generatePlayer('Akeal Hosein', 'Bowler', 'CSK', 'West Indies'),
  generatePlayer('Matt Henry', 'Bowler', 'CSK', 'New Zealand'),
  generatePlayer('Rahul Chahar', 'Bowler', 'CSK'),

  // Delhi Capitals
  generatePlayer('KL Rahul', 'WK-Batter', 'DC', 'India', 93),
  generatePlayer('Karun Nair', 'Batter', 'DC'),
  generatePlayer('David Miller', 'Batter', 'DC', 'South Africa', 90),
  generatePlayer('Ben Duckett', 'WK-Batter', 'DC', 'England'),
  generatePlayer('Pathum Nissanka', 'Batter', 'DC', 'Sri Lanka'),
  generatePlayer('Sahil Parakh', 'Batter', 'DC'),
  generatePlayer('Prithvi Shaw', 'Batter', 'DC'),
  generatePlayer('Abishek Porel', 'WK-Batter', 'DC'),
  generatePlayer('Tristan Stubbs', 'WK-Batter', 'DC', 'South Africa', 91),
  generatePlayer('Axar Patel', 'All-Rounder', 'DC', 'India', 92),
  generatePlayer('Sameer Rizvi', 'All-Rounder', 'DC'),
  generatePlayer('Ashutosh Sharma', 'All-Rounder', 'DC'),
  generatePlayer('Vipraj Nigam', 'All-Rounder', 'DC'),
  generatePlayer('Ajay Mandal', 'All-Rounder', 'DC'),
  generatePlayer('Tripurana Vijay', 'All-Rounder', 'DC'),
  generatePlayer('Madhav Tiwari', 'All-Rounder', 'DC'),
  generatePlayer('Auqib Dar', 'All-Rounder', 'DC'),
  generatePlayer('Nitish Rana', 'All-Rounder', 'DC'),
  generatePlayer('Mitchell Starc', 'Bowler', 'DC', 'Australia', 95),
  generatePlayer('T. Natarajan', 'Bowler', 'DC'),
  generatePlayer('Mukesh Kumar', 'Bowler', 'DC'),
  generatePlayer('Dushmantha Chameera', 'Bowler', 'DC', 'Sri Lanka'),
  generatePlayer('Lungisani Ngidi', 'Bowler', 'DC', 'South Africa'),
  generatePlayer('Kyle Jamieson', 'Bowler', 'DC', 'New Zealand'),
  generatePlayer('Kuldeep Yadav', 'Bowler', 'DC', 'India', 94),

  // Gujarat Titans
  generatePlayer('Shubman Gill', 'Batter', 'GT', 'India', 95),
  generatePlayer('Jos Buttler', 'WK-Batter', 'GT', 'England', 94),
  generatePlayer('Kumar Kushagra', 'WK-Batter', 'GT'),
  generatePlayer('Anuj Rawat', 'WK-Batter', 'GT'),
  generatePlayer('Tom Banton', 'WK-Batter', 'GT', 'England'),
  generatePlayer('Glenn Phillips', 'Batter', 'GT', 'New Zealand'),
  generatePlayer('Nishant Sindhu', 'All-Rounder', 'GT'),
  generatePlayer('Washington Sundar', 'All-Rounder', 'GT'),
  generatePlayer('Mohd. Arshad Khan', 'All-Rounder', 'GT'),
  generatePlayer('Sai Kishore', 'All-Rounder', 'GT'),
  generatePlayer('Jayant Yadav', 'All-Rounder', 'GT'),
  generatePlayer('Jason Holder', 'All-Rounder', 'GT', 'West Indies'),
  generatePlayer('Sai Sudharsan', 'All-Rounder', 'GT', 'India', 88),
  generatePlayer('Shahrukh Khan', 'All-Rounder', 'GT'),
  generatePlayer('Kagiso Rabada', 'Bowler', 'GT', 'South Africa', 93),
  generatePlayer('Mohammed Siraj', 'Bowler', 'GT', 'India', 91),
  generatePlayer('Prasidh Krishna', 'Bowler', 'GT'),
  generatePlayer('Manav Suthar', 'Bowler', 'GT'),
  generatePlayer('Gurnoor Singh Brar', 'Bowler', 'GT'),
  generatePlayer('Ishant Sharma', 'Bowler', 'GT'),
  generatePlayer('Ashok Sharma', 'Bowler', 'GT'),
  generatePlayer('Prithvi Raj Yarra', 'Bowler', 'GT'),
  generatePlayer('Luke Wood', 'Bowler', 'GT', 'England'),
  generatePlayer('Rahul Tewatia', 'Bowler', 'GT'),
  generatePlayer('Rashid Khan', 'Bowler', 'GT', 'Afghanistan', 96),

  // Kolkata Knight Riders
  generatePlayer('Ajinkya Rahane', 'Batter', 'KKR'),
  generatePlayer('Rinku Singh', 'Batter', 'KKR', 'India', 90),
  generatePlayer('Angkrish Raghuvanshi', 'Batter', 'KKR'),
  generatePlayer('Manish Pandey', 'Batter', 'KKR'),
  generatePlayer('Cameron Green', 'Batter', 'KKR', 'Australia', 91),
  generatePlayer('Finn Allen', 'WK-Batter', 'KKR', 'New Zealand'),
  generatePlayer('Tejasvi Singh', 'WK-Batter', 'KKR'),
  generatePlayer('Rahul Tripathi', 'Batter', 'KKR'),
  generatePlayer('Tim Seifert', 'WK-Batter', 'KKR', 'New Zealand'),
  generatePlayer('Rovman Powell', 'Batter', 'KKR', 'West Indies'),
  generatePlayer('Anukul Roy', 'All-Rounder', 'KKR'),
  generatePlayer('Sarthak Ranjan', 'All-Rounder', 'KKR'),
  generatePlayer('Daksh Kamra', 'All-Rounder', 'KKR'),
  generatePlayer('Rachin Ravindra', 'All-Rounder', 'KKR', 'New Zealand', 89),
  generatePlayer('Ramandeep Singh', 'All-Rounder', 'KKR'),
  generatePlayer('Vaibhav Arora', 'Bowler', 'KKR'),
  generatePlayer('Matheesha Pathirana', 'Bowler', 'KKR', 'Sri Lanka', 92),
  generatePlayer('Kartik Tyagi', 'Bowler', 'KKR'),
  generatePlayer('Prashant Solanki', 'Bowler', 'KKR'),
  generatePlayer('Mustafizur Rahman', 'Bowler', 'KKR', 'Bangladesh'),
  generatePlayer('Akash Deep', 'Bowler', 'KKR'),
  generatePlayer('Harshit Rana', 'Bowler', 'KKR'),
  generatePlayer('Umran Malik', 'Bowler', 'KKR'),
  generatePlayer('Sunil Narine', 'Bowler', 'KKR', 'West Indies', 95),
  generatePlayer('Varun Chakaravarthy', 'Bowler', 'KKR', 'India', 90),

  // Lucknow Super Giants
  generatePlayer('Rishabh Pant', 'WK-Batter', 'LSG', 'India', 94),
  generatePlayer('Aiden Markram', 'Batter', 'LSG', 'South Africa', 90),
  generatePlayer('Himmat Singh', 'Batter', 'LSG'),
  generatePlayer('Matthew Breetzke', 'Batter', 'LSG', 'South Africa'),
  generatePlayer('Mukul Choudhary', 'WK-Batter', 'LSG'),
  generatePlayer('Akshat Raghuwanshi', 'Batter', 'LSG'),
  generatePlayer('Josh Inglis', 'WK-Batter', 'LSG', 'Australia'),
  generatePlayer('Nicholas Pooran', 'WK-Batter', 'LSG', 'West Indies', 93),
  generatePlayer('Mitchell Marsh', 'All-Rounder', 'LSG', 'Australia', 91),
  generatePlayer('Abdul Samad', 'All-Rounder', 'LSG'),
  generatePlayer('Shahbaz Ahamad', 'All-Rounder', 'LSG'),
  generatePlayer('Arshin Kulkarni', 'All-Rounder', 'LSG'),
  generatePlayer('Wanindu Hasaranga', 'All-Rounder', 'LSG', 'Sri Lanka', 92),
  generatePlayer('Ayush Badoni', 'All-Rounder', 'LSG'),
  generatePlayer('Mohammad Shami', 'Bowler', 'LSG', 'India', 94),
  generatePlayer('Avesh Khan', 'Bowler', 'LSG'),
  generatePlayer('M. Siddharth', 'Bowler', 'LSG'),
  generatePlayer('Digvesh Singh', 'Bowler', 'LSG'),
  generatePlayer('Akash Singh', 'Bowler', 'LSG'),
  generatePlayer('Prince Yadav', 'Bowler', 'LSG'),
  generatePlayer('Arjun Tendulkar', 'Bowler', 'LSG'),
  generatePlayer('Anrich Nortje', 'Bowler', 'LSG', 'South Africa', 92),
  generatePlayer('Naman Tiwari', 'Bowler', 'LSG'),
  generatePlayer('Mayank Yadav', 'Bowler', 'LSG', 'India', 89),
  generatePlayer('Mohsin Khan', 'Bowler', 'LSG'),

  // Mumbai Indians
  generatePlayer('Rohit Sharma', 'Batter', 'MI', 'India', 94),
  generatePlayer('Surya Kumar Yadav', 'Batter', 'MI', 'India', 96),
  generatePlayer('Robin Minz', 'WK-Batter', 'MI'),
  generatePlayer('Sherfane Rutherford', 'Batter', 'MI', 'West Indies'),
  generatePlayer('Ryan Rickelton', 'WK-Batter', 'MI', 'South Africa'),
  generatePlayer('Quinton de Kock', 'WK-Batter', 'MI', 'South Africa', 92),
  generatePlayer('Danish Malewar', 'Batter', 'MI'),
  generatePlayer('N. Tilak Varma', 'Batter', 'MI', 'India', 90),
  generatePlayer('Hardik Pandya', 'All-Rounder', 'MI', 'India', 94),
  generatePlayer('Naman Dhir', 'All-Rounder', 'MI'),
  generatePlayer('Mitchell Santner', 'All-Rounder', 'MI', 'New Zealand'),
  generatePlayer('Raj Angad Bawa', 'All-Rounder', 'MI'),
  generatePlayer('Atharva Ankolekar', 'All-Rounder', 'MI'),
  generatePlayer('Mayank Rawat', 'All-Rounder', 'MI'),
  generatePlayer('Corbin Bosch', 'All-Rounder', 'MI', 'South Africa'),
  generatePlayer('Will Jacks', 'All-Rounder', 'MI', 'England', 89),
  generatePlayer('Shardul Thakur', 'All-Rounder', 'MI'),
  generatePlayer('Trent Boult', 'Bowler', 'MI', 'New Zealand', 93),
  generatePlayer('Mayank Markande', 'Bowler', 'MI'),
  generatePlayer('Deepak Chahar', 'Bowler', 'MI'),
  generatePlayer('Ashwani Kumar', 'Bowler', 'MI'),
  generatePlayer('Raghu Sharma', 'Bowler', 'MI'),
  generatePlayer('Mohammad Izhar', 'Bowler', 'MI'),
  generatePlayer('Allah Ghazanfar', 'Bowler', 'MI', 'Afghanistan'),
  generatePlayer('Jasprit Bumrah', 'Bowler', 'MI', 'India', 98),

  // Punjab Kings
  generatePlayer('Shreyas Iyer', 'Batter', 'PBKS', 'India', 91),
  generatePlayer('Nehal Wadhera', 'Batter', 'PBKS'),
  generatePlayer('Vishnu Vinod', 'WK-Batter', 'PBKS'),
  generatePlayer('Harnoor Pannu', 'Batter', 'PBKS'),
  generatePlayer('Pyla Avinash', 'Batter', 'PBKS'),
  generatePlayer('Prabhsimran Singh', 'WK-Batter', 'PBKS'),
  generatePlayer('Shashank Singh', 'Batter', 'PBKS'),
  generatePlayer('Marcus Stoinis', 'All-Rounder', 'PBKS', 'Australia', 90),
  generatePlayer('Harpreet Brar', 'All-Rounder', 'PBKS'),
  generatePlayer('Marco Jansen', 'All-Rounder', 'PBKS', 'South Africa', 89),
  generatePlayer('Azmatullah Omarzai', 'All-Rounder', 'PBKS', 'Afghanistan'),
  generatePlayer('Priyansh Arya', 'All-Rounder', 'PBKS'),
  generatePlayer('Musheer Khan', 'All-Rounder', 'PBKS'),
  generatePlayer('Suryansh Shedge', 'All-Rounder', 'PBKS'),
  generatePlayer('Mitch Owen', 'Batter', 'PBKS', 'Australia'),
  generatePlayer('Cooper Connolly', 'All-Rounder', 'PBKS', 'Australia'),
  generatePlayer('Ben Dwarshuis', 'All-Rounder', 'PBKS', 'Australia'),
  generatePlayer('Arshdeep Singh', 'Bowler', 'PBKS', 'India', 92),
  generatePlayer('Yuzvendra Chahal', 'Bowler', 'PBKS', 'India', 91),
  generatePlayer('Vyshak Vijaykumar', 'Bowler', 'PBKS'),
  generatePlayer('Yash Thakur', 'Bowler', 'PBKS'),
  generatePlayer('Xavier Bartlett', 'Bowler', 'PBKS', 'Australia'),
  generatePlayer('Pravin Dubey', 'Bowler', 'PBKS'),
  generatePlayer('Vishal Nishad', 'Bowler', 'PBKS'),
  generatePlayer('Lockie Ferguson', 'Bowler', 'PBKS', 'New Zealand', 90),

  // Rajasthan Royals
  generatePlayer('Shubham Dubey', 'Batter', 'RR'),
  generatePlayer('Vaibhav Suryavanshi', 'Batter', 'RR'),
  generatePlayer('Donovan Ferreira', 'WK-Batter', 'RR', 'South Africa'),
  generatePlayer('Lhuan-dre Pretorius', 'Batter', 'RR', 'South Africa'),
  generatePlayer('Ravi Singh', 'WK-Batter', 'RR'),
  generatePlayer('Aman Rao Perala', 'Batter', 'RR'),
  generatePlayer('Shimron Hetmyer', 'Batter', 'RR', 'West Indies', 89),
  generatePlayer('Yashasvi Jaiswal', 'Batter', 'RR', 'India', 94),
  generatePlayer('Dhruv Jurel', 'WK-Batter', 'RR', 'India', 88),
  generatePlayer('Riyan Parag', 'Batter', 'RR', 'India', 89),
  generatePlayer('Yudhvir Singh Charak', 'All-Rounder', 'RR'),
  generatePlayer('Ravindra Jadeja', 'All-Rounder', 'RR', 'India', 95),
  generatePlayer('Sam Curran', 'All-Rounder', 'RR', 'England', 91),
  generatePlayer('Jofra Archer', 'Bowler', 'RR', 'England', 93),
  generatePlayer('Tushar Deshpande', 'Bowler', 'RR'),
  generatePlayer('Kwena Maphaka', 'Bowler', 'RR', 'South Africa'),
  generatePlayer('Ravi Bishnoi', 'Bowler', 'RR', 'India', 91),
  generatePlayer('Sushant Mishra', 'Bowler', 'RR'),
  generatePlayer('Yash Raj Punja', 'Bowler', 'RR'),
  generatePlayer('Vignesh Puthur', 'Bowler', 'RR'),
  generatePlayer('Brijesh Sharma', 'Bowler', 'RR'),
  generatePlayer('Adam Milne', 'Bowler', 'RR', 'New Zealand'),
  generatePlayer('Kuldeep Sen', 'Bowler', 'RR'),
  generatePlayer('Sandeep Sharma', 'Bowler', 'RR'),
  generatePlayer('Nandre Burger', 'Bowler', 'RR', 'South Africa'),

  // Royal Challengers Bengaluru
  generatePlayer('Rajat Patidar', 'Batter', 'RCB', 'India', 90),
  generatePlayer('Devdutt Padikkal', 'Batter', 'RCB'),
  generatePlayer('Virat Kohli', 'Batter', 'RCB', 'India', 97),
  generatePlayer('Phil Salt', 'WK-Batter', 'RCB', 'England', 92),
  generatePlayer('Jitesh Sharma', 'WK-Batter', 'RCB'),
  generatePlayer('Jordan Cox', 'WK-Batter', 'RCB', 'England'),
  generatePlayer('Krunal Pandya', 'All-Rounder', 'RCB'),
  generatePlayer('Swapnil Singh', 'All-Rounder', 'RCB'),
  generatePlayer('Tim David', 'All-Rounder', 'RCB', 'Australia', 89),
  generatePlayer('Romario Shepherd', 'All-Rounder', 'RCB', 'West Indies'),
  generatePlayer('Jacob Bethell', 'All-Rounder', 'RCB', 'England'),
  generatePlayer('Venkatesh Iyer', 'All-Rounder', 'RCB', 'India', 89),
  generatePlayer('Satvik Deswal', 'All-Rounder', 'RCB'),
  generatePlayer('Mangesh Yadav', 'All-Rounder', 'RCB'),
  generatePlayer('Vicky Ostwal', 'All-Rounder', 'RCB'),
  generatePlayer('Vihaan Malhotra', 'All-Rounder', 'RCB'),
  generatePlayer('Kanishk Chouhan', 'All-Rounder', 'RCB'),
  generatePlayer('Josh Hazlewood', 'Bowler', 'RCB', 'Australia', 95),
  generatePlayer('Rasikh Dar', 'Bowler', 'RCB'),
  generatePlayer('Suyash Sharma', 'Bowler', 'RCB'),
  generatePlayer('Bhuvneshwar Kumar', 'Bowler', 'RCB', 'India', 91),
  generatePlayer('Nuwan Thushara', 'Bowler', 'RCB', 'Sri Lanka'),
  generatePlayer('Abhinandan Singh', 'Bowler', 'RCB'),
  generatePlayer('Jacob Duffy', 'Bowler', 'RCB', 'New Zealand'),
  generatePlayer('Yash Dayal', 'Bowler', 'RCB'),
];
